[package]
name = "pico-pico-fermi-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Using fastrand because being cryptographically secure isn't required here
fastrand = "1.7.0"